# Generated by Django 5.1.7 on 2025-03-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=2555)),
                ('age', models.IntegerField(null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('education_degree', models.CharField(max_length=255, null=True)),
                ('economic_status', models.CharField(choices=[('G', 'Good'), ('N', 'Normal'), ('B', 'Bad')], default='N', max_length=2)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('work_address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiseases',
            fields=[
                ('related_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customerStatus.createcustomer')),
                ('heart_attack', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('pacemaker', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('stroke', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('nervous_disorder', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('asthma', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('epilepsy', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('kidney_disorder', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('liver_disorder', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('addiction', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('tuberculosis', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('stomach_ulcer', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('allergy', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('aids', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('hepatitis', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('insomnia', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('cancer', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('radiotherapy', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('women_pregnancy', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('related_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customerStatus.createcustomer')),
                ('health_now', models.CharField(choices=[('EH', 'Excellent'), ('GH', 'Good'), ('NH', 'Normal'), ('BH', 'Bad')], default='GH', max_length=2)),
                ('last_examination', models.DateTimeField(null=True)),
                ('is_under_care_now', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('have_surgery', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('have_blood_pressure', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('have_sugar', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('bee_hospitalization', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('have_allergy', models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2)),
                ('used_milicent', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
